sudo: required
services:
  - docker

before_install:
  - docker build -t alexander/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexander/docker-react npm run test -- --coverage